#!/usr/bin/tcsh -f
set build_args=""
set clone_script=run_git_clone
\rm -f $clone_script >& /dev/null
\cp -p `realpath $0 | xargs dirname`/../../../package_build/python3.13/22.04/$clone_script .
foreach f (run_dora smlp_regr_patch.sh tkagg_patch.sh run_mathsat_build.sh)
    \cp -fp  `realpath $0 | xargs dirname`/../22.04/$f .
end
if($#argv > 0) then
    if("-rebuild_smlp" == "$argv[1]" ) then
        set build_args="--build-arg CACHE_BUST_SMLP=`git ls-remote https://github.com/SMLP-Systems/smlp.git refs/heads/smlp_python313 | cut -f1`"
    else
        echo "\nUsage: `realpath $0 | xargs basename` [-rebuild_smlp]\n"
        exit 0
    endif
endif
set cmd="env DOCKER_BUILDKIT=1 docker build $build_args --progress=plain -t smlp-test-build-24.04-python313 ."
echo $cmd
$cmd
