#!/usr/bin/tcsh -f
set examples = ( \
    examples/constraint_dora/smlp/run_constraint_dora_poly \
    examples/bnh/smlp/run_poly_pareto \
    examples/eggholder/smlp/run_eggholder \
    examples/si/smlp/run_si_tests )
foreach e ( $examples )
    $e -clean
    if( $#argv > 0 ) then
        if("-clean" == "$argv[1]") then
            echo Cleaning $e:h
            continue
        endif
    endif
    echo Starting: $e
    $e
    echo DONE: $e
    echo =============================================
end
