#!/usr/bin/tcsh -f
set build_args=""
set image=smlp-manylinux_2_28-python311
set wheel=smlp-0.1.0-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
\rm -f $wheel >& /dev/null
set cmd="env DOCKER_BUILDKIT=1 docker build --no-cache --build-arg GIT_BRANCH=`git branch --show-current` --progress=plain -t $image ."
echo $cmd
$cmd
if($status) then
    echo "\nERROR: Docker build failed\n"
    exit 1
else
    set container=dummy
    docker create --name $container $image
    docker cp ${container}:/app/smlp/dist/$wheel .
    docker rm $container
endif
if(-s $wheel ) then
    echo "\nWheel: `realpath $wheel`\n"
    exit 0
else
    echo "\nERROR: failed to copy $wheel to host\n"
    exit 1
endif
