FROM almalinux:9

# ---------------------------------------------------------------------------
# 1. System packages
# ---------------------------------------------------------------------------
RUN dnf install -y epel-release && \
    dnf install -y \
        diffutils \
        git \
        jq \
        libgomp \
        glibc-locale-source \
        glibc-langpack-en \
        gzip \
        tar \
        tcsh \
        tzdata \
        vim \
        wget \
        xorg-x11-fonts-Type1 \
        xorg-x11-fonts-misc \
        xorg-x11-server-Xvfb \
        xorg-x11-server-utils \
        xorg-x11-utils \
        procps-ng \
        python3.11 \
        python3.11-devel \
        python3-tkinter && \
    dnf clean all

# ---------------------------------------------------------------------------
# 2. mathsat
# ---------------------------------------------------------------------------
WORKDIR /app
COPY run_mathsat_build .
RUN ./run_mathsat_build && rm -rf /tmp/mathsat*

# ---------------------------------------------------------------------------
# 3. Install pip and setuptools for Python 3.11
# ---------------------------------------------------------------------------
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11 && \
    python3.11 -m pip install --upgrade setuptools

# ---------------------------------------------------------------------------
# 4. Clone smlp (ARG busts the cache to always get latest)
# ---------------------------------------------------------------------------
ARG CACHE_BUST_SMLP
ARG GIT_BRANCH=master
RUN echo "Building image for branch: $GIT_BRANCH"
COPY run_git_clone /app
RUN cd /app && ./run_git_clone $GIT_BRANCH

# ---------------------------------------------------------------------------
# 5. Install smlp from wheel
# ---------------------------------------------------------------------------
RUN python3.11 -m pip install -i https://test.pypi.org/simple --extra-index-url https://pypi.org/simple smlptech==1.2.0rc1 

# ---------------------------------------------------------------------------
# 6. Configure UTF-8 locale
# ---------------------------------------------------------------------------
RUN localedef -i en_US -f UTF-8 en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# ---------------------------------------------------------------------------
# 7. SMLP regression patch
# ---------------------------------------------------------------------------
COPY smlp_regr_patch .
RUN ./smlp_regr_patch

# ---------------------------------------------------------------------------
# 8. Define python version
# ---------------------------------------------------------------------------
RUN ln -sf /usr/bin/python3.11 /usr/bin/python && \
    ln -sf /usr/bin/python3.11 /usr/bin/python3

# ---------------------------------------------------------------------------
# 9. Copy and run DORA
# ---------------------------------------------------------------------------
COPY run_dora /app
RUN ./run_dora

# ---------------------------------------------------------------------------
# 10. Copy script for opening virtual display - needed for regression
# ---------------------------------------------------------------------------
COPY open_virtual_display /app

# Default command
CMD ["/usr/bin/bash"]
