#!/usr/bin/tcsh -f
set script_path=`realpath $0 | xargs dirname`
\rm -f bnh_p*_optimization_results.json BNH* *.log >& /dev/null
foreach v (X1 X2 F1 F2) 
    \rm -f bnh_pareto_$v.txt >& /dev/null
end
if($#argv > 0) then
    if("-clean" == "$argv[1]") then
        exit(0)
    endif
endif
foreach p (`seq 1 6`)
    ${script_path}/run_bnh_poly_p $p
end
foreach v (X1 X2 F1 F2) 
    grep -h $v bnh_p*_optimization_results.json | cut -d: -f2 | tr -d ' ,' > bnh_pareto_$v.txt
end
${script_path}/plot_results.py -timeout 5
