#!/usr/bin/tcsh -f
set script_path=`realpath $0 | xargs dirname`
if($#argv > 0 ) then
    if("-clean" == "$argv[1]") then
        \rm -rf $script_path/build $HOME/.local_smlp >& /dev/null
        exit(0)
    endif
endif
$script_path/run_meson_build
if(0 == $status) then
    $script_path/run_ninja_build
endif
