#!/usr/bin/tcsh -f
set script_path=`realpath $0 | xargs dirname`
set build_dir=$script_path/build
set output_dir=$HOME/.local_smlp
set kay_dir=$output_dir/kay
\rm -rf $build_dir $output_dir logs.log >& /dev/null
git clone ssh://git@github.com/fbrausse/kay $kay_dir
\rm -rf venv >& /dev/null
/usr/bin/python3.12 -m venv venv
source venv/bin/activate.csh
pip install meson
rehash
meson setup \
    --wipe \
    -Dkay-prefix=$kay_dir \
    --prefix $output_dir $build_dir
/usr/bin/ninja -C build install
\cp -rp ${HOME}/.local_smlp/lib/python3/dist-packages/smlp venv/lib/python3.12/site-packages
pip install -r $script_path:h:h/tutorial/config/requirements_312.txt
$script_path:h:h/tutorial/smlp_dora/run_smlp_dora
