#!/usr/bin/tcsh -f
\mkdir -p $HOME/.local
env PYTHONPATH=/usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages/bin/meson setup --wipe -Dkay-prefix=$HOME/github/kay --prefix $HOME/.local build
