#!/usr/bin/tcsh -f
mkdir -p $HOME/shared
if( ! $?TZ ) setenv TZ `readlink /etc/localtime | sed 's@/usr/share/zoneinfo/@@'`
@ p = 5900
@ d = 99
while( `ss -tln | grep -c :${p}` > 0 )
    @ p = $p + 1
    @ d = $d + 1
end
docker run -e TZ=$TZ -e DISPLAY=:${d} -p ${p}:${p} -v $HOME/shared:/shared -it python311-dev:latest $*
