#!/usr/bin/tcsh -f
wget --tries=5 --timeout=30 --waitretry=2 https://archives.boost.io/release/1.83.0/source/boost_1_83_0.tar.gz -O /tmp/boost_1_83_0.tar.gz
cd /tmp
tar -xvf boost_1_83_0.tar.gz >&  boost_1_83_0.tar.log
cd boost_1_83_0
./bootstrap.sh --with-python=/usr/bin/python3.11 --with-libraries=python
./b2 install --prefix=$HOME/boost_py311 --with-python python=3.11
set arch=`uname -m`
cp -p $HOME/boost_py311/lib/libboost_python311.a /usr/lib/{arch}-linux-gnu
cp -p $HOME/boost_py311/lib/libboost_python311.so.1.83.0 /usr/lib/${arch}-linux-gnu
ln -s /usr/lib/${arch}_64-linux-gnu/{libboost_python311.so.1.83.0,libboost_python311.so}
