#!/usr/bin/tcsh -f
Xvfb $DISPLAY -screen 0 1280x1024x16 >& Xvfb.log &
sleep 2
set d=`echo $DISPLAY | tr -d :`
@ p = $d + 5801
x11vnc -display $DISPLAY -forever -nopw -shared -rfbport $p >& x11nc.log &
autocutsel -selection CLIPBOARD -fork
autocutsel -selection PRIMARY -fork
if(`xset q >& /dev/null ; echo $status` == 0) then
    echo "VNC server has started successfully"
else
   echo "VNC server failed - GUI won't work"
endif
