#!/usr/bin/tcsh -f
set build_args=""
set image=smlp-manylinux_2_28-python313
set wheel=smlp-0.1.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
set clone_script=run_git_clone
\rm -f $wheel >& /dev/null
\rm -f $clone_script >& /dev/null
\cp -p `realpath $0 | xargs dirname`/../22.04/$clone_script .
env DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain -t $image .
if($status) then
    echo "\nERROR: Docker build faied\n"
    exit 1
else
    set container=dummy
    docker create --name $container $image
    docker cp ${container}:/app/smlp/dist/$wheel .
    docker rm $container
endif
if(-s $wheel ) then
    echo "\nWheel: `realpath $wheel`\n"
    exit 0
else
    echo "\nERROR: failed to copy $wheel to host\n"
    exit 1
endif
