#!/usr/bin/tcsh -f
set build_args=""
set clone_script=run_git_clone
\rm -f $clone_script >& /dev/null
\cp -p `realpath $0 | xargs dirname`/../../../package_build/python3.11/22.04/$clone_script .
if($#argv > 0) then
    if("-rebuild_smlp" == "$argv[1]" ) then
        set build_args="--build-arg CACHE_BUST_SMLP=`git ls-remote https://github.com/SMLP-Systems/smlp.git refs/heads/smlp_python311 | cut -f1`"
    else
        echo "\nUsage: `realpath $0 | xargs basename` [-rebuild_smlp]\n"
        exit 0
    endif
endif
set cmd="env DOCKER_BUILDKIT=1 docker build $build_args --progress=plain -t smlp-test-build-22.04-python311 ."
echo $cmd
$cmd
