#!/usr/bin/tcsh -f
set build_args=""
set image=smlp-manylinux_2_28-python312
set wheel=smlp-0.1.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl
\rm -f $wheel >& /dev/null
if($#argv > 0) then
    if("-rebuild_smlp" == "$argv[1]" ) then
        set build_args="--build-arg CACHE_BUST_SMLP=`date +%s`"
    else
        echo "\nUsage: `realpath $0 | xargs basename` [-rebuild_smlp]\n"
        exit 0
    endif
endif
set cmd="env DOCKER_BUILDKIT=1 docker build $build_args --progress=plain -t $image ."
echo $cmd
$cmd
if($status) then
    echo "\nERROR: Docker build faied\n"
    exit 1
else
    set container=dummy
    docker create --name $container $image
    docker cp ${container}:/app/smlp/dist/$wheel .
    docker rm $container
endif
if(-s $wheel ) then
    echo "\nWheel: `realpath $wheel`\n"
    exit 0
else
    echo "\nERROR: failed to copy $wheel to host\n"
    exit 1
endif
