#!/usr/bin/tcsh -f
set clone_script=run_git_clone
\rm -f $clone_script >& /dev/null
\cp -p `realpath $0 | xargs dirname`/../../../package_build/python3.13/22.04/$clone_script .
foreach f (run_dora smlp_regr_patch.sh tkagg_patch.sh run_mathsat_build.sh)
    \cp -fp  `realpath $0 | xargs dirname`/../22.04/$f .
end
\cp -p `realpath $0 | xargs dirname`/../../../package_build/python3.13/22.04/$clone_script .
env DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain -t smlp-test-build-24.04-python313 .
