#!/usr/bin/env bash
image=mdmitry1/python311-dev:latest
if [ $# -gt 0 ]; then 
    image=$1
fi
log=$(realpath $0 | xargs basename).$(echo $image | tr / _ | cut -d: -f1).log
\rm -f $log &> /dev/null
docker run --rm $image /bin/bash -c './open_virtual_display && env DISPLAY=:99 smlp/src/run_smlp.py -h' &> $log
if [ "1" -eq $(grep -c ^usage $log) ]; then
    echo ""
    echo "SMLP installation for $image succeeded"
    echo ""
else
    echo ""
    echo "ERROR: SMLP installation for $image failed" 
    echo ""
    echo "Error messages:"
    grep -i error $log
    echo ""
    exit 1 
fi
