#!/usr/bin/env bash
set -euo pipefail

mkdir -p "$HOME/shared"

if [ -z "${TZ:-}" ]; then
    TZ=$(readlink /etc/localtime | sed 's|.*/zoneinfo/||')
    export TZ
fi

p=5900
d=99

while lsof -i ":$p" | grep -q ":${p}"; do
    ((p++))
    ((d++))
done

docker run --platform linux/arm64 \
    -e TZ="$TZ" \
    -e DISPLAY=":${d}" \
    -p "${p}:${p}" \
    -v "$HOME/shared:/shared" \
    -it \
    mdmitry1/python313-dev-mac:latest \
    "$@"
