#!/usr/bin/tcsh -f
set image=smlp-build-22.04-python313
set wheel=smlp-0.1.0-cp313-cp313-manylinux_2_34_x86_64.whl
env DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain -t smlp-build-22.04-python313 .
if($status) then
    echo "\nERROR: Docker build faied\n"
    exit 1
else
    set container=dummy
    docker create --name $container $image
    docker cp ${container}:/app/smlp/dist/$wheel .
    docker rm $container
endif
if(-s $wheel ) then
    echo "\nWheel: `realpath $wheel`\n"
    exit 0
else
    echo "\nERROR: failed to copy $wheel to host\n"
    exit 1
endif
