name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-15-intel is an Intel runner, macos-14 is Apple silicon
        #os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-14]
        os: [ubuntu-24.04]

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.1
        env:
          CIBW_SKIP: cp*-musllinux_*
          CIBW_BEFORE_ALL: >
            dnf install wget &&
            source {package}/.github/workflows/install-gmp.sh install &&
            source {package}/.github/workflows/install-z3.sh install &&
            export GMP_ROOT=$gmp_R &&
            export Z3_PREFIX=$z3_R &&
            export LD_LIBRARY_PATH=$z3_R/lib:$gmp_R/lib &&
            :
        #   CIBW_SOME_OPTION: value
        #   ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
